In [5]:
%matplotlib inline

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score

df = pd.read_csv('Iris_clean.csv')

training_set = df[['sepal_lenth_cm','sepal_width_cm','petal_length_cm','petal_width_cm']].values
training_class = df['class'].values

random_forest_classifier = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=4, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

cv_scores = cross_val_score(random_forest_classifier, training_set, training_class, cv=10)

(training_inputs,
testing_inputs,
training_classes,
testing_classes) = train_test_split(training_set, training_class, train_size=0.75)

random_forest_classifier.fit(training_set, training_class)

for input_feature, prediction, actual in zip(testing_inputs,
                                             random_forest_classifier.predict(testing_inputs),
                                             testing_classes):
    print('{}\t-->\t{}\t(Actual:{})'.format(input_feature, prediction, actual))

[ 4.9  3.1  1.5  0.1]	-->	setosa	(Actual:setosa)
[ 5.9  3.   5.1  1.8]	-->	virginica	(Actual:virginica)
[ 5.8  2.7  3.9  1.2]	-->	versicolor	(Actual:versicolor)
[ 5.7  3.   4.2  1.2]	-->	versicolor	(Actual:versicolor)
[ 6.3  2.5  5.   1.9]	-->	virginica	(Actual:virginica)
[ 4.8  3.4  1.6  0.2]	-->	setosa	(Actual:setosa)
[ 6.5  2.8  4.6  1.5]	-->	versicolor	(Actual:versicolor)
[ 5.6  2.9  3.6  1.3]	-->	versicolor	(Actual:versicolor)
[ 6.1  2.9  4.7  1.4]	-->	versicolor	(Actual:versicolor)
[ 4.6  3.2  1.4  0.2]	-->	setosa	(Actual:setosa)
[ 4.4  2.9  1.4  0.2]	-->	setosa	(Actual:setosa)
[ 4.3  3.   1.1  0.1]	-->	setosa	(Actual:setosa)
[ 7.7  2.8  6.7  2. ]	-->	virginica	(Actual:virginica)
[ 6.5  3.   5.5  1.8]	-->	virginica	(Actual:virginica)
[ 6.7  3.3  5.7  2.5]	-->	virginica	(Actual:virginica)
[ 4.7  3.2  1.6  0.2]	-->	setosa	(Actual:setosa)
[ 6.   2.7  5.1  1.6]	-->	versicolor	(Actual:versicolor)
[ 5.7  2.5  5.   2. ]	-->	virginica	(Actual:virginica)
[ 6.9  3.1  5.1  2.3]	-->	virginic